export const DummyData = [
  {
    serialNumber: 1,
    mediaName: 'video1.mp4',
    documentName: 'doc1',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 1, 2022, 6:41 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 2,
    mediaName: 'video2.mp4',
    documentName: 'doc2',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 2, 2022, 6:42 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 3,
    mediaName: 'video3.mp4',
    documentName: 'doc3',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 3, 2022, 6:43 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 4,
    mediaName: 'video4.mp4',
    documentName: 'doc4',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 4, 2022, 6:44 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 5,
    mediaName: 'video5.mp4',
    documentName: 'doc5',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 5, 2022, 6:45 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 6,
    mediaName: 'video6.mp4',
    documentName: 'doc6',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 6, 2022, 6:46 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 7,
    mediaName: 'video7.mp4',
    documentName: 'doc7',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 7, 2022, 6:47 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 8,
    mediaName: 'video8.mp4',
    documentName: 'doc8',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 8, 2022, 6:48 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 9,
    mediaName: 'video9.mp4',
    documentName: 'doc9',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 9, 2022, 6:49 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 10,
    mediaName: 'video10.mp4',
    documentName: 'doc10',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 10, 2022, 6:40 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 11,
    mediaName: 'video.11mp4',
    documentName: 'doc11',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. ,11 2022, 6:41 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
  {
    serialNumber: 12,
    mediaName: 'video12.mp4',
    documentName: 'doc12',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    creationTime: 'Nov. 12, 2022, 6:42 p.m.',
    modifyTime: 'Nov. 1, 2022, 6:41 p.m.',
  },
];
